export type StudyRoom = {
	id: string
	building: string
	roomNumber: string
	capacity: number
	features: string[]
	floor: number
	isQuiet: boolean
	hasWhiteboard: boolean
	hasMonitor: boolean
}

export const STUDY_ROOMS: StudyRoom[] = [
	{
		id: 'lib-201',
		building: 'Main Library',
		roomNumber: '201',
		floor: 2,
		capacity: 4,
		features: ['whiteboard', 'quiet', 'near coffee'],
		isQuiet: true,
		hasWhiteboard: true,
		hasMonitor: false,
	},
	{
		id: 'lib-305',
		building: 'Main Library',
		roomNumber: '305',
		floor: 3,
		capacity: 6,
		features: ['whiteboard', 'monitor'],
		isQuiet: false,
		hasWhiteboard: true,
		hasMonitor: true,
	},
	{
		id: 'lib-410',
		building: 'Main Library',
		roomNumber: '410',
		floor: 4,
		capacity: 10,
		features: ['quiet', 'near coffee'],
		isQuiet: true,
		hasWhiteboard: false,
		hasMonitor: true,
	},
	{
		id: 'sci-120',
		building: 'Science Center',
		roomNumber: '120',
		floor: 1,
		capacity: 2,
		features: ['whiteboard', 'near coffee'],
		isQuiet: false,
		hasWhiteboard: true,
		hasMonitor: false,
	},
	{
		id: 'sci-245',
		building: 'Science Center',
		roomNumber: '245',
		floor: 2,
		capacity: 8,
		features: ['whiteboard', 'quiet'],
		isQuiet: true,
		hasWhiteboard: true,
		hasMonitor: false,
	},
	{
		id: 'sci-330',
		building: 'Science Center',
		roomNumber: '330',
		floor: 3,
		capacity: 12,
		features: ['monitor'],
		isQuiet: false,
		hasWhiteboard: false,
		hasMonitor: true,
	},
	{
		id: 'eng-101',
		building: 'Engineering Hall',
		roomNumber: '101',
		floor: 1,
		capacity: 3,
		features: ['quiet'],
		isQuiet: true,
		hasWhiteboard: false,
		hasMonitor: false,
	},
	{
		id: 'eng-210',
		building: 'Engineering Hall',
		roomNumber: '210',
		floor: 2,
		capacity: 5,
		features: ['whiteboard', 'monitor', 'near coffee'],
		isQuiet: false,
		hasWhiteboard: true,
		hasMonitor: true,
	},
	{
		id: 'eng-325',
		building: 'Engineering Hall',
		roomNumber: '325',
		floor: 3,
		capacity: 8,
		features: ['whiteboard', 'quiet'],
		isQuiet: true,
		hasWhiteboard: true,
		hasMonitor: false,
	},
	{
		id: 'bus-210',
		building: 'Business School',
		roomNumber: '210',
		floor: 2,
		capacity: 6,
		features: ['monitor', 'near coffee'],
		isQuiet: false,
		hasWhiteboard: false,
		hasMonitor: true,
	},
	{
		id: 'bus-315',
		building: 'Business School',
		roomNumber: '315',
		floor: 3,
		capacity: 10,
		features: ['whiteboard', 'monitor'],
		isQuiet: false,
		hasWhiteboard: true,
		hasMonitor: true,
	},
	{
		id: 'bus-402',
		building: 'Business School',
		roomNumber: '402',
		floor: 4,
		capacity: 12,
		features: ['whiteboard', 'quiet'],
		isQuiet: true,
		hasWhiteboard: true,
		hasMonitor: false,
	},
]

